/*
 * zipper-pay API
 * Payment service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.pay.sdk.api;

import com.zipper.pay.sdk.ApiCallback;
import com.zipper.pay.sdk.ApiClient;
import com.zipper.pay.sdk.ApiException;
import com.zipper.pay.sdk.ApiResponse;
import com.zipper.pay.sdk.Configuration;
import com.zipper.pay.sdk.Pair;
import com.zipper.pay.sdk.ProgressRequestBody;
import com.zipper.pay.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.zipper.pay.sdk.model.AdminAdjustmentResponseDto;
import com.zipper.pay.sdk.model.AdminCreditRequestDto;
import com.zipper.pay.sdk.model.AdminDebitRequestDto;
import com.zipper.pay.sdk.model.AuthenticatedPrincipal;
import com.zipper.pay.sdk.model.WalletDto;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AdminWalletsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AdminWalletsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AdminWalletsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for credit
     * @param userId  (required)
     * @param currency  (required)
     * @param principal  (required)
     * @param adminCreditRequestDto  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call creditCall(@javax.annotation.Nonnull String userId, @javax.annotation.Nonnull String currency, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull AdminCreditRequestDto adminCreditRequestDto, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = adminCreditRequestDto;

        // create path and map variables
        String localVarPath = "/api/v1/admin/wallets/{userId}/{currency}/credit"
            .replace("{" + "userId" + "}", localVarApiClient.escapeString(userId.toString()))
            .replace("{" + "currency" + "}", localVarApiClient.escapeString(currency.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (principal != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("principal", principal));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call creditValidateBeforeCall(@javax.annotation.Nonnull String userId, @javax.annotation.Nonnull String currency, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull AdminCreditRequestDto adminCreditRequestDto, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'userId' is set
        if (userId == null) {
            throw new ApiException("Missing the required parameter 'userId' when calling credit(Async)");
        }

        // verify the required parameter 'currency' is set
        if (currency == null) {
            throw new ApiException("Missing the required parameter 'currency' when calling credit(Async)");
        }

        // verify the required parameter 'principal' is set
        if (principal == null) {
            throw new ApiException("Missing the required parameter 'principal' when calling credit(Async)");
        }

        // verify the required parameter 'adminCreditRequestDto' is set
        if (adminCreditRequestDto == null) {
            throw new ApiException("Missing the required parameter 'adminCreditRequestDto' when calling credit(Async)");
        }

        return creditCall(userId, currency, principal, adminCreditRequestDto, _callback);

    }

    /**
     * 
     * 
     * @param userId  (required)
     * @param currency  (required)
     * @param principal  (required)
     * @param adminCreditRequestDto  (required)
     * @return AdminAdjustmentResponseDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public AdminAdjustmentResponseDto credit(@javax.annotation.Nonnull String userId, @javax.annotation.Nonnull String currency, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull AdminCreditRequestDto adminCreditRequestDto) throws ApiException {
        ApiResponse<AdminAdjustmentResponseDto> localVarResp = creditWithHttpInfo(userId, currency, principal, adminCreditRequestDto);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param userId  (required)
     * @param currency  (required)
     * @param principal  (required)
     * @param adminCreditRequestDto  (required)
     * @return ApiResponse&lt;AdminAdjustmentResponseDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AdminAdjustmentResponseDto> creditWithHttpInfo(@javax.annotation.Nonnull String userId, @javax.annotation.Nonnull String currency, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull AdminCreditRequestDto adminCreditRequestDto) throws ApiException {
        okhttp3.Call localVarCall = creditValidateBeforeCall(userId, currency, principal, adminCreditRequestDto, null);
        Type localVarReturnType = new TypeToken<AdminAdjustmentResponseDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param userId  (required)
     * @param currency  (required)
     * @param principal  (required)
     * @param adminCreditRequestDto  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call creditAsync(@javax.annotation.Nonnull String userId, @javax.annotation.Nonnull String currency, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull AdminCreditRequestDto adminCreditRequestDto, final ApiCallback<AdminAdjustmentResponseDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = creditValidateBeforeCall(userId, currency, principal, adminCreditRequestDto, _callback);
        Type localVarReturnType = new TypeToken<AdminAdjustmentResponseDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for debit
     * @param userId  (required)
     * @param currency  (required)
     * @param principal  (required)
     * @param adminDebitRequestDto  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call debitCall(@javax.annotation.Nonnull String userId, @javax.annotation.Nonnull String currency, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull AdminDebitRequestDto adminDebitRequestDto, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = adminDebitRequestDto;

        // create path and map variables
        String localVarPath = "/api/v1/admin/wallets/{userId}/{currency}/debit"
            .replace("{" + "userId" + "}", localVarApiClient.escapeString(userId.toString()))
            .replace("{" + "currency" + "}", localVarApiClient.escapeString(currency.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (principal != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("principal", principal));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call debitValidateBeforeCall(@javax.annotation.Nonnull String userId, @javax.annotation.Nonnull String currency, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull AdminDebitRequestDto adminDebitRequestDto, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'userId' is set
        if (userId == null) {
            throw new ApiException("Missing the required parameter 'userId' when calling debit(Async)");
        }

        // verify the required parameter 'currency' is set
        if (currency == null) {
            throw new ApiException("Missing the required parameter 'currency' when calling debit(Async)");
        }

        // verify the required parameter 'principal' is set
        if (principal == null) {
            throw new ApiException("Missing the required parameter 'principal' when calling debit(Async)");
        }

        // verify the required parameter 'adminDebitRequestDto' is set
        if (adminDebitRequestDto == null) {
            throw new ApiException("Missing the required parameter 'adminDebitRequestDto' when calling debit(Async)");
        }

        return debitCall(userId, currency, principal, adminDebitRequestDto, _callback);

    }

    /**
     * 
     * 
     * @param userId  (required)
     * @param currency  (required)
     * @param principal  (required)
     * @param adminDebitRequestDto  (required)
     * @return AdminAdjustmentResponseDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public AdminAdjustmentResponseDto debit(@javax.annotation.Nonnull String userId, @javax.annotation.Nonnull String currency, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull AdminDebitRequestDto adminDebitRequestDto) throws ApiException {
        ApiResponse<AdminAdjustmentResponseDto> localVarResp = debitWithHttpInfo(userId, currency, principal, adminDebitRequestDto);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param userId  (required)
     * @param currency  (required)
     * @param principal  (required)
     * @param adminDebitRequestDto  (required)
     * @return ApiResponse&lt;AdminAdjustmentResponseDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AdminAdjustmentResponseDto> debitWithHttpInfo(@javax.annotation.Nonnull String userId, @javax.annotation.Nonnull String currency, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull AdminDebitRequestDto adminDebitRequestDto) throws ApiException {
        okhttp3.Call localVarCall = debitValidateBeforeCall(userId, currency, principal, adminDebitRequestDto, null);
        Type localVarReturnType = new TypeToken<AdminAdjustmentResponseDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param userId  (required)
     * @param currency  (required)
     * @param principal  (required)
     * @param adminDebitRequestDto  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call debitAsync(@javax.annotation.Nonnull String userId, @javax.annotation.Nonnull String currency, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull AdminDebitRequestDto adminDebitRequestDto, final ApiCallback<AdminAdjustmentResponseDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = debitValidateBeforeCall(userId, currency, principal, adminDebitRequestDto, _callback);
        Type localVarReturnType = new TypeToken<AdminAdjustmentResponseDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listWallets
     * @param userId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listWalletsCall(@javax.annotation.Nonnull String userId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/admin/wallets/{userId}"
            .replace("{" + "userId" + "}", localVarApiClient.escapeString(userId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listWalletsValidateBeforeCall(@javax.annotation.Nonnull String userId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'userId' is set
        if (userId == null) {
            throw new ApiException("Missing the required parameter 'userId' when calling listWallets(Async)");
        }

        return listWalletsCall(userId, _callback);

    }

    /**
     * 
     * 
     * @param userId  (required)
     * @return List&lt;WalletDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public List<WalletDto> listWallets(@javax.annotation.Nonnull String userId) throws ApiException {
        ApiResponse<List<WalletDto>> localVarResp = listWalletsWithHttpInfo(userId);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param userId  (required)
     * @return ApiResponse&lt;List&lt;WalletDto&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<WalletDto>> listWalletsWithHttpInfo(@javax.annotation.Nonnull String userId) throws ApiException {
        okhttp3.Call localVarCall = listWalletsValidateBeforeCall(userId, null);
        Type localVarReturnType = new TypeToken<List<WalletDto>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param userId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listWalletsAsync(@javax.annotation.Nonnull String userId, final ApiCallback<List<WalletDto>> _callback) throws ApiException {

        okhttp3.Call localVarCall = listWalletsValidateBeforeCall(userId, _callback);
        Type localVarReturnType = new TypeToken<List<WalletDto>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
