/*
 * zipper-pay API
 * Payment service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.pay.sdk.api;

import com.zipper.pay.sdk.ApiCallback;
import com.zipper.pay.sdk.ApiClient;
import com.zipper.pay.sdk.ApiException;
import com.zipper.pay.sdk.ApiResponse;
import com.zipper.pay.sdk.Configuration;
import com.zipper.pay.sdk.Pair;
import com.zipper.pay.sdk.ProgressRequestBody;
import com.zipper.pay.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.zipper.pay.sdk.model.AuthenticatedPrincipal;
import com.zipper.pay.sdk.model.ConversionRateRequestDto;
import com.zipper.pay.sdk.model.ConversionRateResponseDto;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AdminConversionRatesApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AdminConversionRatesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AdminConversionRatesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for insert
     * @param principal  (required)
     * @param conversionRateRequestDto  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call insertCall(@javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull ConversionRateRequestDto conversionRateRequestDto, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = conversionRateRequestDto;

        // create path and map variables
        String localVarPath = "/api/v1/admin/conversion-rates";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (principal != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("principal", principal));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call insertValidateBeforeCall(@javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull ConversionRateRequestDto conversionRateRequestDto, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'principal' is set
        if (principal == null) {
            throw new ApiException("Missing the required parameter 'principal' when calling insert(Async)");
        }

        // verify the required parameter 'conversionRateRequestDto' is set
        if (conversionRateRequestDto == null) {
            throw new ApiException("Missing the required parameter 'conversionRateRequestDto' when calling insert(Async)");
        }

        return insertCall(principal, conversionRateRequestDto, _callback);

    }

    /**
     * 
     * 
     * @param principal  (required)
     * @param conversionRateRequestDto  (required)
     * @return ConversionRateResponseDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ConversionRateResponseDto insert(@javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull ConversionRateRequestDto conversionRateRequestDto) throws ApiException {
        ApiResponse<ConversionRateResponseDto> localVarResp = insertWithHttpInfo(principal, conversionRateRequestDto);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param principal  (required)
     * @param conversionRateRequestDto  (required)
     * @return ApiResponse&lt;ConversionRateResponseDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ConversionRateResponseDto> insertWithHttpInfo(@javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull ConversionRateRequestDto conversionRateRequestDto) throws ApiException {
        okhttp3.Call localVarCall = insertValidateBeforeCall(principal, conversionRateRequestDto, null);
        Type localVarReturnType = new TypeToken<ConversionRateResponseDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param principal  (required)
     * @param conversionRateRequestDto  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call insertAsync(@javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull ConversionRateRequestDto conversionRateRequestDto, final ApiCallback<ConversionRateResponseDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = insertValidateBeforeCall(principal, conversionRateRequestDto, _callback);
        Type localVarReturnType = new TypeToken<ConversionRateResponseDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for list1
     * @param paymentMethod  (optional)
     * @param moneyCurrency  (optional)
     * @param creditCurrency  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call list1Call(@javax.annotation.Nullable String paymentMethod, @javax.annotation.Nullable String moneyCurrency, @javax.annotation.Nullable String creditCurrency, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/admin/conversion-rates";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (paymentMethod != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("paymentMethod", paymentMethod));
        }

        if (moneyCurrency != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("moneyCurrency", moneyCurrency));
        }

        if (creditCurrency != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("creditCurrency", creditCurrency));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call list1ValidateBeforeCall(@javax.annotation.Nullable String paymentMethod, @javax.annotation.Nullable String moneyCurrency, @javax.annotation.Nullable String creditCurrency, final ApiCallback _callback) throws ApiException {
        return list1Call(paymentMethod, moneyCurrency, creditCurrency, _callback);

    }

    /**
     * 
     * 
     * @param paymentMethod  (optional)
     * @param moneyCurrency  (optional)
     * @param creditCurrency  (optional)
     * @return List&lt;ConversionRateResponseDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public List<ConversionRateResponseDto> list1(@javax.annotation.Nullable String paymentMethod, @javax.annotation.Nullable String moneyCurrency, @javax.annotation.Nullable String creditCurrency) throws ApiException {
        ApiResponse<List<ConversionRateResponseDto>> localVarResp = list1WithHttpInfo(paymentMethod, moneyCurrency, creditCurrency);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param paymentMethod  (optional)
     * @param moneyCurrency  (optional)
     * @param creditCurrency  (optional)
     * @return ApiResponse&lt;List&lt;ConversionRateResponseDto&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<ConversionRateResponseDto>> list1WithHttpInfo(@javax.annotation.Nullable String paymentMethod, @javax.annotation.Nullable String moneyCurrency, @javax.annotation.Nullable String creditCurrency) throws ApiException {
        okhttp3.Call localVarCall = list1ValidateBeforeCall(paymentMethod, moneyCurrency, creditCurrency, null);
        Type localVarReturnType = new TypeToken<List<ConversionRateResponseDto>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param paymentMethod  (optional)
     * @param moneyCurrency  (optional)
     * @param creditCurrency  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call list1Async(@javax.annotation.Nullable String paymentMethod, @javax.annotation.Nullable String moneyCurrency, @javax.annotation.Nullable String creditCurrency, final ApiCallback<List<ConversionRateResponseDto>> _callback) throws ApiException {

        okhttp3.Call localVarCall = list1ValidateBeforeCall(paymentMethod, moneyCurrency, creditCurrency, _callback);
        Type localVarReturnType = new TypeToken<List<ConversionRateResponseDto>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
