/*
 * zipper-pay API
 * Payment service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.pay.sdk.api;

import com.zipper.pay.sdk.ApiCallback;
import com.zipper.pay.sdk.ApiClient;
import com.zipper.pay.sdk.ApiException;
import com.zipper.pay.sdk.ApiResponse;
import com.zipper.pay.sdk.Configuration;
import com.zipper.pay.sdk.Pair;
import com.zipper.pay.sdk.ProgressRequestBody;
import com.zipper.pay.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.zipper.pay.sdk.model.AdminPaymentIntentDetailDto;
import com.zipper.pay.sdk.model.PageResponseListAdminPaymentIntentRowDto;
import com.zipper.pay.sdk.model.SearchPaymentIntentsRequest;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AdminPaymentIntentsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AdminPaymentIntentsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AdminPaymentIntentsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for adminGetPaymentIntent
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminGetPaymentIntentCall(@javax.annotation.Nonnull UUID id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/admin/payment-intents/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call adminGetPaymentIntentValidateBeforeCall(@javax.annotation.Nonnull UUID id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling adminGetPaymentIntent(Async)");
        }

        return adminGetPaymentIntentCall(id, _callback);

    }

    /**
     * Get one payment intent
     * The full record, its line items and its refund chain.
     * @param id  (required)
     * @return AdminPaymentIntentDetailDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public AdminPaymentIntentDetailDto adminGetPaymentIntent(@javax.annotation.Nonnull UUID id) throws ApiException {
        ApiResponse<AdminPaymentIntentDetailDto> localVarResp = adminGetPaymentIntentWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Get one payment intent
     * The full record, its line items and its refund chain.
     * @param id  (required)
     * @return ApiResponse&lt;AdminPaymentIntentDetailDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<AdminPaymentIntentDetailDto> adminGetPaymentIntentWithHttpInfo(@javax.annotation.Nonnull UUID id) throws ApiException {
        okhttp3.Call localVarCall = adminGetPaymentIntentValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<AdminPaymentIntentDetailDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get one payment intent (asynchronously)
     * The full record, its line items and its refund chain.
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminGetPaymentIntentAsync(@javax.annotation.Nonnull UUID id, final ApiCallback<AdminPaymentIntentDetailDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = adminGetPaymentIntentValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<AdminPaymentIntentDetailDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for adminSearchPaymentIntents
     * @param searchPaymentIntentsRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminSearchPaymentIntentsCall(@javax.annotation.Nonnull SearchPaymentIntentsRequest searchPaymentIntentsRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = searchPaymentIntentsRequest;

        // create path and map variables
        String localVarPath = "/api/v1/admin/payment-intents/search";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call adminSearchPaymentIntentsValidateBeforeCall(@javax.annotation.Nonnull SearchPaymentIntentsRequest searchPaymentIntentsRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'searchPaymentIntentsRequest' is set
        if (searchPaymentIntentsRequest == null) {
            throw new ApiException("Missing the required parameter 'searchPaymentIntentsRequest' when calling adminSearchPaymentIntents(Async)");
        }

        return adminSearchPaymentIntentsCall(searchPaymentIntentsRequest, _callback);

    }

    /**
     * Search payment intents
     * Search, filter, sort and page payment intents. Admin only.
     * @param searchPaymentIntentsRequest  (required)
     * @return PageResponseListAdminPaymentIntentRowDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public PageResponseListAdminPaymentIntentRowDto adminSearchPaymentIntents(@javax.annotation.Nonnull SearchPaymentIntentsRequest searchPaymentIntentsRequest) throws ApiException {
        ApiResponse<PageResponseListAdminPaymentIntentRowDto> localVarResp = adminSearchPaymentIntentsWithHttpInfo(searchPaymentIntentsRequest);
        return localVarResp.getData();
    }

    /**
     * Search payment intents
     * Search, filter, sort and page payment intents. Admin only.
     * @param searchPaymentIntentsRequest  (required)
     * @return ApiResponse&lt;PageResponseListAdminPaymentIntentRowDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PageResponseListAdminPaymentIntentRowDto> adminSearchPaymentIntentsWithHttpInfo(@javax.annotation.Nonnull SearchPaymentIntentsRequest searchPaymentIntentsRequest) throws ApiException {
        okhttp3.Call localVarCall = adminSearchPaymentIntentsValidateBeforeCall(searchPaymentIntentsRequest, null);
        Type localVarReturnType = new TypeToken<PageResponseListAdminPaymentIntentRowDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Search payment intents (asynchronously)
     * Search, filter, sort and page payment intents. Admin only.
     * @param searchPaymentIntentsRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call adminSearchPaymentIntentsAsync(@javax.annotation.Nonnull SearchPaymentIntentsRequest searchPaymentIntentsRequest, final ApiCallback<PageResponseListAdminPaymentIntentRowDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = adminSearchPaymentIntentsValidateBeforeCall(searchPaymentIntentsRequest, _callback);
        Type localVarReturnType = new TypeToken<PageResponseListAdminPaymentIntentRowDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
