/*
 * zipper-pay API
 * Payment service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.pay.sdk.api;

import com.zipper.pay.sdk.ApiCallback;
import com.zipper.pay.sdk.ApiClient;
import com.zipper.pay.sdk.ApiException;
import com.zipper.pay.sdk.ApiResponse;
import com.zipper.pay.sdk.Configuration;
import com.zipper.pay.sdk.Pair;
import com.zipper.pay.sdk.ProgressRequestBody;
import com.zipper.pay.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.zipper.pay.sdk.model.AuthenticatedPrincipal;
import com.zipper.pay.sdk.model.RefundRequestDto;
import com.zipper.pay.sdk.model.RefundResponseDto;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class InternalRefundsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public InternalRefundsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public InternalRefundsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for refundPaymentIntent
     * @param intentId  (required)
     * @param idempotencyKey  (required)
     * @param principal  (required)
     * @param refundRequestDto  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call refundPaymentIntentCall(@javax.annotation.Nonnull UUID intentId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull RefundRequestDto refundRequestDto, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = refundRequestDto;

        // create path and map variables
        String localVarPath = "/api/v1/internal/payment-intents/{intentId}/refunds"
            .replace("{" + "intentId" + "}", localVarApiClient.escapeString(intentId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (principal != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("principal", principal));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }


        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call refundPaymentIntentValidateBeforeCall(@javax.annotation.Nonnull UUID intentId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull RefundRequestDto refundRequestDto, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'intentId' is set
        if (intentId == null) {
            throw new ApiException("Missing the required parameter 'intentId' when calling refundPaymentIntent(Async)");
        }

        // verify the required parameter 'idempotencyKey' is set
        if (idempotencyKey == null) {
            throw new ApiException("Missing the required parameter 'idempotencyKey' when calling refundPaymentIntent(Async)");
        }

        // verify the required parameter 'principal' is set
        if (principal == null) {
            throw new ApiException("Missing the required parameter 'principal' when calling refundPaymentIntent(Async)");
        }

        // verify the required parameter 'refundRequestDto' is set
        if (refundRequestDto == null) {
            throw new ApiException("Missing the required parameter 'refundRequestDto' when calling refundPaymentIntent(Async)");
        }

        return refundPaymentIntentCall(intentId, idempotencyKey, principal, refundRequestDto, _callback);

    }

    /**
     * 
     * 
     * @param intentId  (required)
     * @param idempotencyKey  (required)
     * @param principal  (required)
     * @param refundRequestDto  (required)
     * @return RefundResponseDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public RefundResponseDto refundPaymentIntent(@javax.annotation.Nonnull UUID intentId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull RefundRequestDto refundRequestDto) throws ApiException {
        ApiResponse<RefundResponseDto> localVarResp = refundPaymentIntentWithHttpInfo(intentId, idempotencyKey, principal, refundRequestDto);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param intentId  (required)
     * @param idempotencyKey  (required)
     * @param principal  (required)
     * @param refundRequestDto  (required)
     * @return ApiResponse&lt;RefundResponseDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RefundResponseDto> refundPaymentIntentWithHttpInfo(@javax.annotation.Nonnull UUID intentId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull RefundRequestDto refundRequestDto) throws ApiException {
        okhttp3.Call localVarCall = refundPaymentIntentValidateBeforeCall(intentId, idempotencyKey, principal, refundRequestDto, null);
        Type localVarReturnType = new TypeToken<RefundResponseDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param intentId  (required)
     * @param idempotencyKey  (required)
     * @param principal  (required)
     * @param refundRequestDto  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call refundPaymentIntentAsync(@javax.annotation.Nonnull UUID intentId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull RefundRequestDto refundRequestDto, final ApiCallback<RefundResponseDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = refundPaymentIntentValidateBeforeCall(intentId, idempotencyKey, principal, refundRequestDto, _callback);
        Type localVarReturnType = new TypeToken<RefundResponseDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for refundWalletCharge
     * @param chargeId  (required)
     * @param idempotencyKey  (required)
     * @param principal  (required)
     * @param refundRequestDto  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call refundWalletChargeCall(@javax.annotation.Nonnull UUID chargeId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull RefundRequestDto refundRequestDto, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = refundRequestDto;

        // create path and map variables
        String localVarPath = "/api/v1/internal/wallet/charges/{chargeId}/refunds"
            .replace("{" + "chargeId" + "}", localVarApiClient.escapeString(chargeId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (principal != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("principal", principal));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }


        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call refundWalletChargeValidateBeforeCall(@javax.annotation.Nonnull UUID chargeId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull RefundRequestDto refundRequestDto, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'chargeId' is set
        if (chargeId == null) {
            throw new ApiException("Missing the required parameter 'chargeId' when calling refundWalletCharge(Async)");
        }

        // verify the required parameter 'idempotencyKey' is set
        if (idempotencyKey == null) {
            throw new ApiException("Missing the required parameter 'idempotencyKey' when calling refundWalletCharge(Async)");
        }

        // verify the required parameter 'principal' is set
        if (principal == null) {
            throw new ApiException("Missing the required parameter 'principal' when calling refundWalletCharge(Async)");
        }

        // verify the required parameter 'refundRequestDto' is set
        if (refundRequestDto == null) {
            throw new ApiException("Missing the required parameter 'refundRequestDto' when calling refundWalletCharge(Async)");
        }

        return refundWalletChargeCall(chargeId, idempotencyKey, principal, refundRequestDto, _callback);

    }

    /**
     * 
     * 
     * @param chargeId  (required)
     * @param idempotencyKey  (required)
     * @param principal  (required)
     * @param refundRequestDto  (required)
     * @return RefundResponseDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public RefundResponseDto refundWalletCharge(@javax.annotation.Nonnull UUID chargeId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull RefundRequestDto refundRequestDto) throws ApiException {
        ApiResponse<RefundResponseDto> localVarResp = refundWalletChargeWithHttpInfo(chargeId, idempotencyKey, principal, refundRequestDto);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param chargeId  (required)
     * @param idempotencyKey  (required)
     * @param principal  (required)
     * @param refundRequestDto  (required)
     * @return ApiResponse&lt;RefundResponseDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RefundResponseDto> refundWalletChargeWithHttpInfo(@javax.annotation.Nonnull UUID chargeId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull RefundRequestDto refundRequestDto) throws ApiException {
        okhttp3.Call localVarCall = refundWalletChargeValidateBeforeCall(chargeId, idempotencyKey, principal, refundRequestDto, null);
        Type localVarReturnType = new TypeToken<RefundResponseDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param chargeId  (required)
     * @param idempotencyKey  (required)
     * @param principal  (required)
     * @param refundRequestDto  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call refundWalletChargeAsync(@javax.annotation.Nonnull UUID chargeId, @javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull RefundRequestDto refundRequestDto, final ApiCallback<RefundResponseDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = refundWalletChargeValidateBeforeCall(chargeId, idempotencyKey, principal, refundRequestDto, _callback);
        Type localVarReturnType = new TypeToken<RefundResponseDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
