/*
 * zipper-pay API
 * Payment service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.pay.sdk.api;

import com.zipper.pay.sdk.ApiCallback;
import com.zipper.pay.sdk.ApiClient;
import com.zipper.pay.sdk.ApiException;
import com.zipper.pay.sdk.ApiResponse;
import com.zipper.pay.sdk.Configuration;
import com.zipper.pay.sdk.Pair;
import com.zipper.pay.sdk.ProgressRequestBody;
import com.zipper.pay.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.zipper.pay.sdk.model.AuthenticatedPrincipal;
import com.zipper.pay.sdk.model.CreateSubscriptionRequestDto;
import com.zipper.pay.sdk.model.SubscriptionResponseDto;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SubscriptionInternalControllerApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public SubscriptionInternalControllerApi() {
        this(Configuration.getDefaultApiClient());
    }

    public SubscriptionInternalControllerApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for create
     * @param idempotencyKey  (required)
     * @param principal  (required)
     * @param createSubscriptionRequestDto  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull CreateSubscriptionRequestDto createSubscriptionRequestDto, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createSubscriptionRequestDto;

        // create path and map variables
        String localVarPath = "/api/v1/internal/subscriptions";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (principal != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("principal", principal));
        }

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (idempotencyKey != null) {
            localVarHeaderParams.put("Idempotency-Key", localVarApiClient.parameterToString(idempotencyKey));
        }


        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createValidateBeforeCall(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull CreateSubscriptionRequestDto createSubscriptionRequestDto, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'idempotencyKey' is set
        if (idempotencyKey == null) {
            throw new ApiException("Missing the required parameter 'idempotencyKey' when calling create(Async)");
        }

        // verify the required parameter 'principal' is set
        if (principal == null) {
            throw new ApiException("Missing the required parameter 'principal' when calling create(Async)");
        }

        // verify the required parameter 'createSubscriptionRequestDto' is set
        if (createSubscriptionRequestDto == null) {
            throw new ApiException("Missing the required parameter 'createSubscriptionRequestDto' when calling create(Async)");
        }

        return createCall(idempotencyKey, principal, createSubscriptionRequestDto, _callback);

    }

    /**
     * 
     * 
     * @param idempotencyKey  (required)
     * @param principal  (required)
     * @param createSubscriptionRequestDto  (required)
     * @return SubscriptionResponseDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public SubscriptionResponseDto create(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull CreateSubscriptionRequestDto createSubscriptionRequestDto) throws ApiException {
        ApiResponse<SubscriptionResponseDto> localVarResp = createWithHttpInfo(idempotencyKey, principal, createSubscriptionRequestDto);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param idempotencyKey  (required)
     * @param principal  (required)
     * @param createSubscriptionRequestDto  (required)
     * @return ApiResponse&lt;SubscriptionResponseDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SubscriptionResponseDto> createWithHttpInfo(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull CreateSubscriptionRequestDto createSubscriptionRequestDto) throws ApiException {
        okhttp3.Call localVarCall = createValidateBeforeCall(idempotencyKey, principal, createSubscriptionRequestDto, null);
        Type localVarReturnType = new TypeToken<SubscriptionResponseDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param idempotencyKey  (required)
     * @param principal  (required)
     * @param createSubscriptionRequestDto  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call createAsync(@javax.annotation.Nonnull String idempotencyKey, @javax.annotation.Nonnull AuthenticatedPrincipal principal, @javax.annotation.Nonnull CreateSubscriptionRequestDto createSubscriptionRequestDto, final ApiCallback<SubscriptionResponseDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = createValidateBeforeCall(idempotencyKey, principal, createSubscriptionRequestDto, _callback);
        Type localVarReturnType = new TypeToken<SubscriptionResponseDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for get2
     * @param id  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call get2Call(@javax.annotation.Nonnull UUID id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/internal/subscriptions/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call get2ValidateBeforeCall(@javax.annotation.Nonnull UUID id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling get2(Async)");
        }

        return get2Call(id, _callback);

    }

    /**
     * 
     * 
     * @param id  (required)
     * @return SubscriptionResponseDto
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public SubscriptionResponseDto get2(@javax.annotation.Nonnull UUID id) throws ApiException {
        ApiResponse<SubscriptionResponseDto> localVarResp = get2WithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param id  (required)
     * @return ApiResponse&lt;SubscriptionResponseDto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SubscriptionResponseDto> get2WithHttpInfo(@javax.annotation.Nonnull UUID id) throws ApiException {
        okhttp3.Call localVarCall = get2ValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<SubscriptionResponseDto>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param id  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call get2Async(@javax.annotation.Nonnull UUID id, final ApiCallback<SubscriptionResponseDto> _callback) throws ApiException {

        okhttp3.Call localVarCall = get2ValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<SubscriptionResponseDto>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
