/*
 * zipper-pay API
 * Payment service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.pay.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.pay.sdk.JSON;

/**
 * AdminInvoiceDetailDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class AdminInvoiceDetailDto {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Long id;

  public static final String SERIALIZED_NAME_PAYMENT_INTENT_ID = "paymentIntentId";
  @SerializedName(SERIALIZED_NAME_PAYMENT_INTENT_ID)
  @javax.annotation.Nullable
  private UUID paymentIntentId;

  /**
   * Gets or Sets docType
   */
  @JsonAdapter(DocTypeEnum.Adapter.class)
  public enum DocTypeEnum {
    RECEIPT("RECEIPT"),
    
    INVOICE("INVOICE"),
    
    INVRECEIPT("INVRECEIPT"),
    
    CREDIT_INVOICE("CREDIT_INVOICE");

    private String value;

    DocTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DocTypeEnum fromValue(String value) {
      for (DocTypeEnum b : DocTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DocTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DocTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DocTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DocTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      DocTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_DOC_TYPE = "docType";
  @SerializedName(SERIALIZED_NAME_DOC_TYPE)
  @javax.annotation.Nullable
  private DocTypeEnum docType;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    PENDING("PENDING"),
    
    ISSUED("ISSUED"),
    
    FAILED("FAILED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String SERIALIZED_NAME_PROVIDER = "provider";
  @SerializedName(SERIALIZED_NAME_PROVIDER)
  @javax.annotation.Nullable
  private String provider;

  public static final String SERIALIZED_NAME_LANGUAGE = "language";
  @SerializedName(SERIALIZED_NAME_LANGUAGE)
  @javax.annotation.Nullable
  private String language;

  public static final String SERIALIZED_NAME_RETRY_COUNT = "retryCount";
  @SerializedName(SERIALIZED_NAME_RETRY_COUNT)
  @javax.annotation.Nullable
  private Integer retryCount;

  public static final String SERIALIZED_NAME_NEXT_RETRY_AT = "nextRetryAt";
  @SerializedName(SERIALIZED_NAME_NEXT_RETRY_AT)
  @javax.annotation.Nullable
  private OffsetDateTime nextRetryAt;

  public static final String SERIALIZED_NAME_PROVIDER_DOC_ID = "providerDocId";
  @SerializedName(SERIALIZED_NAME_PROVIDER_DOC_ID)
  @javax.annotation.Nullable
  private String providerDocId;

  public static final String SERIALIZED_NAME_DOC_URL = "docUrl";
  @SerializedName(SERIALIZED_NAME_DOC_URL)
  @javax.annotation.Nullable
  private String docUrl;

  public static final String SERIALIZED_NAME_DOC_COPY_URL = "docCopyUrl";
  @SerializedName(SERIALIZED_NAME_DOC_COPY_URL)
  @javax.annotation.Nullable
  private String docCopyUrl;

  public static final String SERIALIZED_NAME_REQUEST_PAYLOAD = "requestPayload";
  @SerializedName(SERIALIZED_NAME_REQUEST_PAYLOAD)
  @javax.annotation.Nullable
  private Map<String, Object> requestPayload = new HashMap<>();

  public static final String SERIALIZED_NAME_RESPONSE_PAYLOAD = "responsePayload";
  @SerializedName(SERIALIZED_NAME_RESPONSE_PAYLOAD)
  @javax.annotation.Nullable
  private Map<String, Object> responsePayload = new HashMap<>();

  public static final String SERIALIZED_NAME_LAST_ERROR = "lastError";
  @SerializedName(SERIALIZED_NAME_LAST_ERROR)
  @javax.annotation.Nullable
  private String lastError;

  public static final String SERIALIZED_NAME_ISSUED_AT = "issuedAt";
  @SerializedName(SERIALIZED_NAME_ISSUED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime issuedAt;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_CREATED_BY = "createdBy";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  @javax.annotation.Nullable
  private String createdBy;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_UPDATED_BY = "updatedBy";
  @SerializedName(SERIALIZED_NAME_UPDATED_BY)
  @javax.annotation.Nullable
  private String updatedBy;

  public AdminInvoiceDetailDto() {
  }

  public AdminInvoiceDetailDto id(@javax.annotation.Nullable Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Long getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }


  public AdminInvoiceDetailDto paymentIntentId(@javax.annotation.Nullable UUID paymentIntentId) {
    this.paymentIntentId = paymentIntentId;
    return this;
  }

  /**
   * Get paymentIntentId
   * @return paymentIntentId
   */
  @javax.annotation.Nullable
  public UUID getPaymentIntentId() {
    return paymentIntentId;
  }

  public void setPaymentIntentId(@javax.annotation.Nullable UUID paymentIntentId) {
    this.paymentIntentId = paymentIntentId;
  }


  public AdminInvoiceDetailDto docType(@javax.annotation.Nullable DocTypeEnum docType) {
    this.docType = docType;
    return this;
  }

  /**
   * Get docType
   * @return docType
   */
  @javax.annotation.Nullable
  public DocTypeEnum getDocType() {
    return docType;
  }

  public void setDocType(@javax.annotation.Nullable DocTypeEnum docType) {
    this.docType = docType;
  }


  public AdminInvoiceDetailDto status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public AdminInvoiceDetailDto provider(@javax.annotation.Nullable String provider) {
    this.provider = provider;
    return this;
  }

  /**
   * Get provider
   * @return provider
   */
  @javax.annotation.Nullable
  public String getProvider() {
    return provider;
  }

  public void setProvider(@javax.annotation.Nullable String provider) {
    this.provider = provider;
  }


  public AdminInvoiceDetailDto language(@javax.annotation.Nullable String language) {
    this.language = language;
    return this;
  }

  /**
   * Get language
   * @return language
   */
  @javax.annotation.Nullable
  public String getLanguage() {
    return language;
  }

  public void setLanguage(@javax.annotation.Nullable String language) {
    this.language = language;
  }


  public AdminInvoiceDetailDto retryCount(@javax.annotation.Nullable Integer retryCount) {
    this.retryCount = retryCount;
    return this;
  }

  /**
   * Get retryCount
   * @return retryCount
   */
  @javax.annotation.Nullable
  public Integer getRetryCount() {
    return retryCount;
  }

  public void setRetryCount(@javax.annotation.Nullable Integer retryCount) {
    this.retryCount = retryCount;
  }


  public AdminInvoiceDetailDto nextRetryAt(@javax.annotation.Nullable OffsetDateTime nextRetryAt) {
    this.nextRetryAt = nextRetryAt;
    return this;
  }

  /**
   * Get nextRetryAt
   * @return nextRetryAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getNextRetryAt() {
    return nextRetryAt;
  }

  public void setNextRetryAt(@javax.annotation.Nullable OffsetDateTime nextRetryAt) {
    this.nextRetryAt = nextRetryAt;
  }


  public AdminInvoiceDetailDto providerDocId(@javax.annotation.Nullable String providerDocId) {
    this.providerDocId = providerDocId;
    return this;
  }

  /**
   * Get providerDocId
   * @return providerDocId
   */
  @javax.annotation.Nullable
  public String getProviderDocId() {
    return providerDocId;
  }

  public void setProviderDocId(@javax.annotation.Nullable String providerDocId) {
    this.providerDocId = providerDocId;
  }


  public AdminInvoiceDetailDto docUrl(@javax.annotation.Nullable String docUrl) {
    this.docUrl = docUrl;
    return this;
  }

  /**
   * Get docUrl
   * @return docUrl
   */
  @javax.annotation.Nullable
  public String getDocUrl() {
    return docUrl;
  }

  public void setDocUrl(@javax.annotation.Nullable String docUrl) {
    this.docUrl = docUrl;
  }


  public AdminInvoiceDetailDto docCopyUrl(@javax.annotation.Nullable String docCopyUrl) {
    this.docCopyUrl = docCopyUrl;
    return this;
  }

  /**
   * Get docCopyUrl
   * @return docCopyUrl
   */
  @javax.annotation.Nullable
  public String getDocCopyUrl() {
    return docCopyUrl;
  }

  public void setDocCopyUrl(@javax.annotation.Nullable String docCopyUrl) {
    this.docCopyUrl = docCopyUrl;
  }


  public AdminInvoiceDetailDto requestPayload(@javax.annotation.Nullable Map<String, Object> requestPayload) {
    this.requestPayload = requestPayload;
    return this;
  }

  public AdminInvoiceDetailDto putRequestPayloadItem(String key, Object requestPayloadItem) {
    if (this.requestPayload == null) {
      this.requestPayload = new HashMap<>();
    }
    this.requestPayload.put(key, requestPayloadItem);
    return this;
  }

  /**
   * Get requestPayload
   * @return requestPayload
   */
  @javax.annotation.Nullable
  public Map<String, Object> getRequestPayload() {
    return requestPayload;
  }

  public void setRequestPayload(@javax.annotation.Nullable Map<String, Object> requestPayload) {
    this.requestPayload = requestPayload;
  }


  public AdminInvoiceDetailDto responsePayload(@javax.annotation.Nullable Map<String, Object> responsePayload) {
    this.responsePayload = responsePayload;
    return this;
  }

  public AdminInvoiceDetailDto putResponsePayloadItem(String key, Object responsePayloadItem) {
    if (this.responsePayload == null) {
      this.responsePayload = new HashMap<>();
    }
    this.responsePayload.put(key, responsePayloadItem);
    return this;
  }

  /**
   * Get responsePayload
   * @return responsePayload
   */
  @javax.annotation.Nullable
  public Map<String, Object> getResponsePayload() {
    return responsePayload;
  }

  public void setResponsePayload(@javax.annotation.Nullable Map<String, Object> responsePayload) {
    this.responsePayload = responsePayload;
  }


  public AdminInvoiceDetailDto lastError(@javax.annotation.Nullable String lastError) {
    this.lastError = lastError;
    return this;
  }

  /**
   * Get lastError
   * @return lastError
   */
  @javax.annotation.Nullable
  public String getLastError() {
    return lastError;
  }

  public void setLastError(@javax.annotation.Nullable String lastError) {
    this.lastError = lastError;
  }


  public AdminInvoiceDetailDto issuedAt(@javax.annotation.Nullable OffsetDateTime issuedAt) {
    this.issuedAt = issuedAt;
    return this;
  }

  /**
   * Get issuedAt
   * @return issuedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getIssuedAt() {
    return issuedAt;
  }

  public void setIssuedAt(@javax.annotation.Nullable OffsetDateTime issuedAt) {
    this.issuedAt = issuedAt;
  }


  public AdminInvoiceDetailDto createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public AdminInvoiceDetailDto createdBy(@javax.annotation.Nullable String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

  /**
   * Get createdBy
   * @return createdBy
   */
  @javax.annotation.Nullable
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(@javax.annotation.Nullable String createdBy) {
    this.createdBy = createdBy;
  }


  public AdminInvoiceDetailDto updatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public AdminInvoiceDetailDto updatedBy(@javax.annotation.Nullable String updatedBy) {
    this.updatedBy = updatedBy;
    return this;
  }

  /**
   * Get updatedBy
   * @return updatedBy
   */
  @javax.annotation.Nullable
  public String getUpdatedBy() {
    return updatedBy;
  }

  public void setUpdatedBy(@javax.annotation.Nullable String updatedBy) {
    this.updatedBy = updatedBy;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminInvoiceDetailDto adminInvoiceDetailDto = (AdminInvoiceDetailDto) o;
    return Objects.equals(this.id, adminInvoiceDetailDto.id) &&
        Objects.equals(this.paymentIntentId, adminInvoiceDetailDto.paymentIntentId) &&
        Objects.equals(this.docType, adminInvoiceDetailDto.docType) &&
        Objects.equals(this.status, adminInvoiceDetailDto.status) &&
        Objects.equals(this.provider, adminInvoiceDetailDto.provider) &&
        Objects.equals(this.language, adminInvoiceDetailDto.language) &&
        Objects.equals(this.retryCount, adminInvoiceDetailDto.retryCount) &&
        Objects.equals(this.nextRetryAt, adminInvoiceDetailDto.nextRetryAt) &&
        Objects.equals(this.providerDocId, adminInvoiceDetailDto.providerDocId) &&
        Objects.equals(this.docUrl, adminInvoiceDetailDto.docUrl) &&
        Objects.equals(this.docCopyUrl, adminInvoiceDetailDto.docCopyUrl) &&
        Objects.equals(this.requestPayload, adminInvoiceDetailDto.requestPayload) &&
        Objects.equals(this.responsePayload, adminInvoiceDetailDto.responsePayload) &&
        Objects.equals(this.lastError, adminInvoiceDetailDto.lastError) &&
        Objects.equals(this.issuedAt, adminInvoiceDetailDto.issuedAt) &&
        Objects.equals(this.createdAt, adminInvoiceDetailDto.createdAt) &&
        Objects.equals(this.createdBy, adminInvoiceDetailDto.createdBy) &&
        Objects.equals(this.updatedAt, adminInvoiceDetailDto.updatedAt) &&
        Objects.equals(this.updatedBy, adminInvoiceDetailDto.updatedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, paymentIntentId, docType, status, provider, language, retryCount, nextRetryAt, providerDocId, docUrl, docCopyUrl, requestPayload, responsePayload, lastError, issuedAt, createdAt, createdBy, updatedAt, updatedBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminInvoiceDetailDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    paymentIntentId: ").append(toIndentedString(paymentIntentId)).append("\n");
    sb.append("    docType: ").append(toIndentedString(docType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    retryCount: ").append(toIndentedString(retryCount)).append("\n");
    sb.append("    nextRetryAt: ").append(toIndentedString(nextRetryAt)).append("\n");
    sb.append("    providerDocId: ").append(toIndentedString(providerDocId)).append("\n");
    sb.append("    docUrl: ").append(toIndentedString(docUrl)).append("\n");
    sb.append("    docCopyUrl: ").append(toIndentedString(docCopyUrl)).append("\n");
    sb.append("    requestPayload: ").append(toIndentedString(requestPayload)).append("\n");
    sb.append("    responsePayload: ").append(toIndentedString(responsePayload)).append("\n");
    sb.append("    lastError: ").append(toIndentedString(lastError)).append("\n");
    sb.append("    issuedAt: ").append(toIndentedString(issuedAt)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("paymentIntentId");
    openapiFields.add("docType");
    openapiFields.add("status");
    openapiFields.add("provider");
    openapiFields.add("language");
    openapiFields.add("retryCount");
    openapiFields.add("nextRetryAt");
    openapiFields.add("providerDocId");
    openapiFields.add("docUrl");
    openapiFields.add("docCopyUrl");
    openapiFields.add("requestPayload");
    openapiFields.add("responsePayload");
    openapiFields.add("lastError");
    openapiFields.add("issuedAt");
    openapiFields.add("createdAt");
    openapiFields.add("createdBy");
    openapiFields.add("updatedAt");
    openapiFields.add("updatedBy");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AdminInvoiceDetailDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AdminInvoiceDetailDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AdminInvoiceDetailDto is not found in the empty JSON string", AdminInvoiceDetailDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AdminInvoiceDetailDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AdminInvoiceDetailDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("paymentIntentId") != null && !jsonObj.get("paymentIntentId").isJsonNull()) && !jsonObj.get("paymentIntentId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `paymentIntentId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paymentIntentId").toString()));
      }
      if ((jsonObj.get("docType") != null && !jsonObj.get("docType").isJsonNull()) && !jsonObj.get("docType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `docType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("docType").toString()));
      }
      // validate the optional field `docType`
      if (jsonObj.get("docType") != null && !jsonObj.get("docType").isJsonNull()) {
        DocTypeEnum.validateJsonElement(jsonObj.get("docType"));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("provider") != null && !jsonObj.get("provider").isJsonNull()) && !jsonObj.get("provider").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `provider` to be a primitive type in the JSON string but got `%s`", jsonObj.get("provider").toString()));
      }
      if ((jsonObj.get("language") != null && !jsonObj.get("language").isJsonNull()) && !jsonObj.get("language").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `language` to be a primitive type in the JSON string but got `%s`", jsonObj.get("language").toString()));
      }
      if ((jsonObj.get("providerDocId") != null && !jsonObj.get("providerDocId").isJsonNull()) && !jsonObj.get("providerDocId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `providerDocId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("providerDocId").toString()));
      }
      if ((jsonObj.get("docUrl") != null && !jsonObj.get("docUrl").isJsonNull()) && !jsonObj.get("docUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `docUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("docUrl").toString()));
      }
      if ((jsonObj.get("docCopyUrl") != null && !jsonObj.get("docCopyUrl").isJsonNull()) && !jsonObj.get("docCopyUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `docCopyUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("docCopyUrl").toString()));
      }
      if ((jsonObj.get("lastError") != null && !jsonObj.get("lastError").isJsonNull()) && !jsonObj.get("lastError").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lastError` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastError").toString()));
      }
      if ((jsonObj.get("createdBy") != null && !jsonObj.get("createdBy").isJsonNull()) && !jsonObj.get("createdBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createdBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdBy").toString()));
      }
      if ((jsonObj.get("updatedBy") != null && !jsonObj.get("updatedBy").isJsonNull()) && !jsonObj.get("updatedBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `updatedBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updatedBy").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AdminInvoiceDetailDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AdminInvoiceDetailDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AdminInvoiceDetailDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AdminInvoiceDetailDto.class));

       return (TypeAdapter<T>) new TypeAdapter<AdminInvoiceDetailDto>() {
           @Override
           public void write(JsonWriter out, AdminInvoiceDetailDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AdminInvoiceDetailDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AdminInvoiceDetailDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AdminInvoiceDetailDto
   * @throws IOException if the JSON string is invalid with respect to AdminInvoiceDetailDto
   */
  public static AdminInvoiceDetailDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AdminInvoiceDetailDto.class);
  }

  /**
   * Convert an instance of AdminInvoiceDetailDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

