/*
 * zipper-pay API
 * Payment service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.pay.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.pay.sdk.JSON;

/**
 * ConfirmCheckoutResponseDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class ConfirmCheckoutResponseDto {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private UUID id;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    PENDING("PENDING"),
    
    AWAITING_METHOD_SELECTION("AWAITING_METHOD_SELECTION"),
    
    AWAITING_PAYMENT("AWAITING_PAYMENT"),
    
    COMPLETED("COMPLETED"),
    
    FAILED("FAILED"),
    
    EXPIRED("EXPIRED"),
    
    REFUNDED("REFUNDED"),
    
    PARTIALLY_REFUNDED("PARTIALLY_REFUNDED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private StatusEnum status;

  /**
   * Gets or Sets selectedPaymentMethod
   */
  @JsonAdapter(SelectedPaymentMethodEnum.Adapter.class)
  public enum SelectedPaymentMethodEnum {
    WALLET("WALLET"),
    
    PAYME("PAYME");

    private String value;

    SelectedPaymentMethodEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SelectedPaymentMethodEnum fromValue(String value) {
      for (SelectedPaymentMethodEnum b : SelectedPaymentMethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SelectedPaymentMethodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SelectedPaymentMethodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SelectedPaymentMethodEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SelectedPaymentMethodEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      SelectedPaymentMethodEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_SELECTED_PAYMENT_METHOD = "selectedPaymentMethod";
  @SerializedName(SERIALIZED_NAME_SELECTED_PAYMENT_METHOD)
  @javax.annotation.Nullable
  private SelectedPaymentMethodEnum selectedPaymentMethod;

  public ConfirmCheckoutResponseDto() {
  }

  public ConfirmCheckoutResponseDto id(@javax.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public UUID getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable UUID id) {
    this.id = id;
  }


  public ConfirmCheckoutResponseDto status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public ConfirmCheckoutResponseDto selectedPaymentMethod(@javax.annotation.Nullable SelectedPaymentMethodEnum selectedPaymentMethod) {
    this.selectedPaymentMethod = selectedPaymentMethod;
    return this;
  }

  /**
   * Get selectedPaymentMethod
   * @return selectedPaymentMethod
   */
  @javax.annotation.Nullable
  public SelectedPaymentMethodEnum getSelectedPaymentMethod() {
    return selectedPaymentMethod;
  }

  public void setSelectedPaymentMethod(@javax.annotation.Nullable SelectedPaymentMethodEnum selectedPaymentMethod) {
    this.selectedPaymentMethod = selectedPaymentMethod;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfirmCheckoutResponseDto confirmCheckoutResponseDto = (ConfirmCheckoutResponseDto) o;
    return Objects.equals(this.id, confirmCheckoutResponseDto.id) &&
        Objects.equals(this.status, confirmCheckoutResponseDto.status) &&
        Objects.equals(this.selectedPaymentMethod, confirmCheckoutResponseDto.selectedPaymentMethod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, selectedPaymentMethod);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfirmCheckoutResponseDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    selectedPaymentMethod: ").append(toIndentedString(selectedPaymentMethod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("status");
    openapiFields.add("selectedPaymentMethod");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConfirmCheckoutResponseDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConfirmCheckoutResponseDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConfirmCheckoutResponseDto is not found in the empty JSON string", ConfirmCheckoutResponseDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConfirmCheckoutResponseDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConfirmCheckoutResponseDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("selectedPaymentMethod") != null && !jsonObj.get("selectedPaymentMethod").isJsonNull()) && !jsonObj.get("selectedPaymentMethod").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `selectedPaymentMethod` to be a primitive type in the JSON string but got `%s`", jsonObj.get("selectedPaymentMethod").toString()));
      }
      // validate the optional field `selectedPaymentMethod`
      if (jsonObj.get("selectedPaymentMethod") != null && !jsonObj.get("selectedPaymentMethod").isJsonNull()) {
        SelectedPaymentMethodEnum.validateJsonElement(jsonObj.get("selectedPaymentMethod"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConfirmCheckoutResponseDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConfirmCheckoutResponseDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConfirmCheckoutResponseDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConfirmCheckoutResponseDto.class));

       return (TypeAdapter<T>) new TypeAdapter<ConfirmCheckoutResponseDto>() {
           @Override
           public void write(JsonWriter out, ConfirmCheckoutResponseDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConfirmCheckoutResponseDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConfirmCheckoutResponseDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConfirmCheckoutResponseDto
   * @throws IOException if the JSON string is invalid with respect to ConfirmCheckoutResponseDto
   */
  public static ConfirmCheckoutResponseDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConfirmCheckoutResponseDto.class);
  }

  /**
   * Convert an instance of ConfirmCheckoutResponseDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

