/*
 * zipper-pay API
 * Payment service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.pay.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.pay.sdk.JSON;

/**
 * ConversionRateRequestDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class ConversionRateRequestDto {
  /**
   * Gets or Sets paymentMethod
   */
  @JsonAdapter(PaymentMethodEnum.Adapter.class)
  public enum PaymentMethodEnum {
    WALLET("WALLET"),
    
    PAYME("PAYME");

    private String value;

    PaymentMethodEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PaymentMethodEnum fromValue(String value) {
      for (PaymentMethodEnum b : PaymentMethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<PaymentMethodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PaymentMethodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PaymentMethodEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return PaymentMethodEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      PaymentMethodEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_PAYMENT_METHOD = "paymentMethod";
  @SerializedName(SERIALIZED_NAME_PAYMENT_METHOD)
  @javax.annotation.Nonnull
  private PaymentMethodEnum paymentMethod;

  public static final String SERIALIZED_NAME_MONEY_CURRENCY = "moneyCurrency";
  @SerializedName(SERIALIZED_NAME_MONEY_CURRENCY)
  @javax.annotation.Nonnull
  private String moneyCurrency;

  public static final String SERIALIZED_NAME_CREDIT_CURRENCY = "creditCurrency";
  @SerializedName(SERIALIZED_NAME_CREDIT_CURRENCY)
  @javax.annotation.Nonnull
  private String creditCurrency;

  public static final String SERIALIZED_NAME_RATE = "rate";
  @SerializedName(SERIALIZED_NAME_RATE)
  @javax.annotation.Nonnull
  private BigDecimal rate;

  public static final String SERIALIZED_NAME_FEE_PERCENT = "feePercent";
  @SerializedName(SERIALIZED_NAME_FEE_PERCENT)
  @javax.annotation.Nullable
  private BigDecimal feePercent;

  public static final String SERIALIZED_NAME_FEE_FIXED = "feeFixed";
  @SerializedName(SERIALIZED_NAME_FEE_FIXED)
  @javax.annotation.Nullable
  private BigDecimal feeFixed;

  public ConversionRateRequestDto() {
  }

  public ConversionRateRequestDto paymentMethod(@javax.annotation.Nonnull PaymentMethodEnum paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

  /**
   * Get paymentMethod
   * @return paymentMethod
   */
  @javax.annotation.Nonnull
  public PaymentMethodEnum getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(@javax.annotation.Nonnull PaymentMethodEnum paymentMethod) {
    this.paymentMethod = paymentMethod;
  }


  public ConversionRateRequestDto moneyCurrency(@javax.annotation.Nonnull String moneyCurrency) {
    this.moneyCurrency = moneyCurrency;
    return this;
  }

  /**
   * Get moneyCurrency
   * @return moneyCurrency
   */
  @javax.annotation.Nonnull
  public String getMoneyCurrency() {
    return moneyCurrency;
  }

  public void setMoneyCurrency(@javax.annotation.Nonnull String moneyCurrency) {
    this.moneyCurrency = moneyCurrency;
  }


  public ConversionRateRequestDto creditCurrency(@javax.annotation.Nonnull String creditCurrency) {
    this.creditCurrency = creditCurrency;
    return this;
  }

  /**
   * Get creditCurrency
   * @return creditCurrency
   */
  @javax.annotation.Nonnull
  public String getCreditCurrency() {
    return creditCurrency;
  }

  public void setCreditCurrency(@javax.annotation.Nonnull String creditCurrency) {
    this.creditCurrency = creditCurrency;
  }


  public ConversionRateRequestDto rate(@javax.annotation.Nonnull BigDecimal rate) {
    this.rate = rate;
    return this;
  }

  /**
   * Get rate
   * minimum: 1.0E-8
   * @return rate
   */
  @javax.annotation.Nonnull
  public BigDecimal getRate() {
    return rate;
  }

  public void setRate(@javax.annotation.Nonnull BigDecimal rate) {
    this.rate = rate;
  }


  public ConversionRateRequestDto feePercent(@javax.annotation.Nullable BigDecimal feePercent) {
    this.feePercent = feePercent;
    return this;
  }

  /**
   * Get feePercent
   * minimum: 0
   * maximum: 100
   * @return feePercent
   */
  @javax.annotation.Nullable
  public BigDecimal getFeePercent() {
    return feePercent;
  }

  public void setFeePercent(@javax.annotation.Nullable BigDecimal feePercent) {
    this.feePercent = feePercent;
  }


  public ConversionRateRequestDto feeFixed(@javax.annotation.Nullable BigDecimal feeFixed) {
    this.feeFixed = feeFixed;
    return this;
  }

  /**
   * Get feeFixed
   * minimum: 0
   * @return feeFixed
   */
  @javax.annotation.Nullable
  public BigDecimal getFeeFixed() {
    return feeFixed;
  }

  public void setFeeFixed(@javax.annotation.Nullable BigDecimal feeFixed) {
    this.feeFixed = feeFixed;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConversionRateRequestDto conversionRateRequestDto = (ConversionRateRequestDto) o;
    return Objects.equals(this.paymentMethod, conversionRateRequestDto.paymentMethod) &&
        Objects.equals(this.moneyCurrency, conversionRateRequestDto.moneyCurrency) &&
        Objects.equals(this.creditCurrency, conversionRateRequestDto.creditCurrency) &&
        Objects.equals(this.rate, conversionRateRequestDto.rate) &&
        Objects.equals(this.feePercent, conversionRateRequestDto.feePercent) &&
        Objects.equals(this.feeFixed, conversionRateRequestDto.feeFixed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentMethod, moneyCurrency, creditCurrency, rate, feePercent, feeFixed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConversionRateRequestDto {\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    moneyCurrency: ").append(toIndentedString(moneyCurrency)).append("\n");
    sb.append("    creditCurrency: ").append(toIndentedString(creditCurrency)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("    feePercent: ").append(toIndentedString(feePercent)).append("\n");
    sb.append("    feeFixed: ").append(toIndentedString(feeFixed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("paymentMethod");
    openapiFields.add("moneyCurrency");
    openapiFields.add("creditCurrency");
    openapiFields.add("rate");
    openapiFields.add("feePercent");
    openapiFields.add("feeFixed");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("paymentMethod");
    openapiRequiredFields.add("moneyCurrency");
    openapiRequiredFields.add("creditCurrency");
    openapiRequiredFields.add("rate");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConversionRateRequestDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConversionRateRequestDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConversionRateRequestDto is not found in the empty JSON string", ConversionRateRequestDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConversionRateRequestDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConversionRateRequestDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ConversionRateRequestDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("paymentMethod").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `paymentMethod` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paymentMethod").toString()));
      }
      // validate the required field `paymentMethod`
      PaymentMethodEnum.validateJsonElement(jsonObj.get("paymentMethod"));
      if (!jsonObj.get("moneyCurrency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `moneyCurrency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("moneyCurrency").toString()));
      }
      if (!jsonObj.get("creditCurrency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `creditCurrency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("creditCurrency").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConversionRateRequestDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConversionRateRequestDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConversionRateRequestDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConversionRateRequestDto.class));

       return (TypeAdapter<T>) new TypeAdapter<ConversionRateRequestDto>() {
           @Override
           public void write(JsonWriter out, ConversionRateRequestDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConversionRateRequestDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConversionRateRequestDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConversionRateRequestDto
   * @throws IOException if the JSON string is invalid with respect to ConversionRateRequestDto
   */
  public static ConversionRateRequestDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConversionRateRequestDto.class);
  }

  /**
   * Convert an instance of ConversionRateRequestDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

