/*
 * zipper-pay API
 * Payment service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.pay.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.zipper.pay.sdk.model.PostingLineDto;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.pay.sdk.JSON;

/**
 * FreeFormJournalRequestDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class FreeFormJournalRequestDto {
  /**
   * Gets or Sets eventType
   */
  @JsonAdapter(EventTypeEnum.Adapter.class)
  public enum EventTypeEnum {
    WALLET_TOPUP("WALLET_TOPUP"),
    
    WALLET_SPEND("WALLET_SPEND"),
    
    REFUND_TOPUP("REFUND_TOPUP"),
    
    REFUND_SPEND("REFUND_SPEND"),
    
    OPENING_BALANCE_FROM_LEGACY("OPENING_BALANCE_FROM_LEGACY"),
    
    ADJUSTMENT_CREDIT("ADJUSTMENT_CREDIT"),
    
    ADJUSTMENT_DEBIT("ADJUSTMENT_DEBIT");

    private String value;

    EventTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static EventTypeEnum fromValue(String value) {
      for (EventTypeEnum b : EventTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<EventTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final EventTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public EventTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return EventTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      EventTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_EVENT_TYPE = "eventType";
  @SerializedName(SERIALIZED_NAME_EVENT_TYPE)
  @javax.annotation.Nonnull
  private EventTypeEnum eventType;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  @javax.annotation.Nonnull
  private String currency;

  public static final String SERIALIZED_NAME_REF_TYPE = "refType";
  @SerializedName(SERIALIZED_NAME_REF_TYPE)
  @javax.annotation.Nullable
  private String refType;

  public static final String SERIALIZED_NAME_REF_ID = "refId";
  @SerializedName(SERIALIZED_NAME_REF_ID)
  @javax.annotation.Nullable
  private String refId;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_POSTINGS = "postings";
  @SerializedName(SERIALIZED_NAME_POSTINGS)
  @javax.annotation.Nonnull
  private List<PostingLineDto> postings = new ArrayList<>();

  public FreeFormJournalRequestDto() {
  }

  public FreeFormJournalRequestDto eventType(@javax.annotation.Nonnull EventTypeEnum eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * Get eventType
   * @return eventType
   */
  @javax.annotation.Nonnull
  public EventTypeEnum getEventType() {
    return eventType;
  }

  public void setEventType(@javax.annotation.Nonnull EventTypeEnum eventType) {
    this.eventType = eventType;
  }


  public FreeFormJournalRequestDto currency(@javax.annotation.Nonnull String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @javax.annotation.Nonnull
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(@javax.annotation.Nonnull String currency) {
    this.currency = currency;
  }


  public FreeFormJournalRequestDto refType(@javax.annotation.Nullable String refType) {
    this.refType = refType;
    return this;
  }

  /**
   * Get refType
   * @return refType
   */
  @javax.annotation.Nullable
  public String getRefType() {
    return refType;
  }

  public void setRefType(@javax.annotation.Nullable String refType) {
    this.refType = refType;
  }


  public FreeFormJournalRequestDto refId(@javax.annotation.Nullable String refId) {
    this.refId = refId;
    return this;
  }

  /**
   * Get refId
   * @return refId
   */
  @javax.annotation.Nullable
  public String getRefId() {
    return refId;
  }

  public void setRefId(@javax.annotation.Nullable String refId) {
    this.refId = refId;
  }


  public FreeFormJournalRequestDto description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public FreeFormJournalRequestDto postings(@javax.annotation.Nonnull List<PostingLineDto> postings) {
    this.postings = postings;
    return this;
  }

  public FreeFormJournalRequestDto addPostingsItem(PostingLineDto postingsItem) {
    if (this.postings == null) {
      this.postings = new ArrayList<>();
    }
    this.postings.add(postingsItem);
    return this;
  }

  /**
   * Get postings
   * @return postings
   */
  @javax.annotation.Nonnull
  public List<PostingLineDto> getPostings() {
    return postings;
  }

  public void setPostings(@javax.annotation.Nonnull List<PostingLineDto> postings) {
    this.postings = postings;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FreeFormJournalRequestDto freeFormJournalRequestDto = (FreeFormJournalRequestDto) o;
    return Objects.equals(this.eventType, freeFormJournalRequestDto.eventType) &&
        Objects.equals(this.currency, freeFormJournalRequestDto.currency) &&
        Objects.equals(this.refType, freeFormJournalRequestDto.refType) &&
        Objects.equals(this.refId, freeFormJournalRequestDto.refId) &&
        Objects.equals(this.description, freeFormJournalRequestDto.description) &&
        Objects.equals(this.postings, freeFormJournalRequestDto.postings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventType, currency, refType, refId, description, postings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FreeFormJournalRequestDto {\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    refType: ").append(toIndentedString(refType)).append("\n");
    sb.append("    refId: ").append(toIndentedString(refId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    postings: ").append(toIndentedString(postings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("eventType");
    openapiFields.add("currency");
    openapiFields.add("refType");
    openapiFields.add("refId");
    openapiFields.add("description");
    openapiFields.add("postings");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("eventType");
    openapiRequiredFields.add("currency");
    openapiRequiredFields.add("postings");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FreeFormJournalRequestDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FreeFormJournalRequestDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FreeFormJournalRequestDto is not found in the empty JSON string", FreeFormJournalRequestDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FreeFormJournalRequestDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `FreeFormJournalRequestDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : FreeFormJournalRequestDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("eventType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `eventType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("eventType").toString()));
      }
      // validate the required field `eventType`
      EventTypeEnum.validateJsonElement(jsonObj.get("eventType"));
      if (!jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
      if ((jsonObj.get("refType") != null && !jsonObj.get("refType").isJsonNull()) && !jsonObj.get("refType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `refType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("refType").toString()));
      }
      if ((jsonObj.get("refId") != null && !jsonObj.get("refId").isJsonNull()) && !jsonObj.get("refId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `refId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("refId").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("postings").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `postings` to be an array in the JSON string but got `%s`", jsonObj.get("postings").toString()));
      }

      JsonArray jsonArraypostings = jsonObj.getAsJsonArray("postings");
      // validate the required field `postings` (array)
      for (int i = 0; i < jsonArraypostings.size(); i++) {
        PostingLineDto.validateJsonElement(jsonArraypostings.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FreeFormJournalRequestDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FreeFormJournalRequestDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FreeFormJournalRequestDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FreeFormJournalRequestDto.class));

       return (TypeAdapter<T>) new TypeAdapter<FreeFormJournalRequestDto>() {
           @Override
           public void write(JsonWriter out, FreeFormJournalRequestDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FreeFormJournalRequestDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FreeFormJournalRequestDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FreeFormJournalRequestDto
   * @throws IOException if the JSON string is invalid with respect to FreeFormJournalRequestDto
   */
  public static FreeFormJournalRequestDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FreeFormJournalRequestDto.class);
  }

  /**
   * Convert an instance of FreeFormJournalRequestDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

