/*
 * zipper-pay API
 * Payment service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.pay.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.zipper.pay.sdk.model.ExchangeRateDto;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import com.zipper.pay.sdk.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class List3200Response extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(List3200Response.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!List3200Response.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'List3200Response' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ExchangeRateDto> adapterExchangeRateDto = gson.getDelegateAdapter(this, TypeToken.get(ExchangeRateDto.class));

            final Type typeInstanceListExchangeRateDto = new TypeToken<List<ExchangeRateDto>>(){}.getType();
            final TypeAdapter<List<ExchangeRateDto>> adapterListExchangeRateDto = (TypeAdapter<List<ExchangeRateDto>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListExchangeRateDto));

            return (TypeAdapter<T>) new TypeAdapter<List3200Response>() {
                @Override
                public void write(JsonWriter out, List3200Response value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `ExchangeRateDto`
                    if (value.getActualInstance() instanceof ExchangeRateDto) {
                        JsonElement element = adapterExchangeRateDto.toJsonTree((ExchangeRateDto)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `List<ExchangeRateDto>`
                    if (value.getActualInstance() instanceof List<?>) {
                        List<?> list = (List<?>) value.getActualInstance();
                        if (list.get(0) instanceof ExchangeRateDto) {
                            JsonArray array = adapterListExchangeRateDto.toJsonTree((List<ExchangeRateDto>)value.getActualInstance()).getAsJsonArray();
                            elementAdapter.write(out, array);
                            return;
                        }
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: ExchangeRateDto, List<ExchangeRateDto>");
                }

                @Override
                public List3200Response read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize ExchangeRateDto
                    try {
                        // validate the JSON object to see if any exception is thrown
                        ExchangeRateDto.validateJsonElement(jsonElement);
                        actualAdapter = adapterExchangeRateDto;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'ExchangeRateDto'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for ExchangeRateDto failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'ExchangeRateDto'", e);
                    }
                    // deserialize List<ExchangeRateDto>
                    try {
                        // validate the JSON object to see if any exception is thrown
                        if (!jsonElement.isJsonArray()) {
                            throw new IllegalArgumentException(String.format("Expected json element to be a array type in the JSON string but got `%s`", jsonElement.toString()));
                        }

                        JsonArray array = jsonElement.getAsJsonArray();
                        // validate array items
                        for(JsonElement element : array) {
                            ExchangeRateDto.validateJsonElement(element);
                        }
                        actualAdapter = adapterListExchangeRateDto;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'List<ExchangeRateDto>'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for List<ExchangeRateDto> failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'List<ExchangeRateDto>'", e);
                    }

                    if (match == 1) {
                        List3200Response ret = new List3200Response();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for List3200Response: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public List3200Response() {
        super("oneOf", Boolean.FALSE);
    }

    public List3200Response(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("ExchangeRateDto", ExchangeRateDto.class);
        schemas.put("List<ExchangeRateDto>", List.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return List3200Response.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * ExchangeRateDto, List<ExchangeRateDto>
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof ExchangeRateDto) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof List<?>) {
            List<?> list = (List<?>) instance;
            if (list.get(0) instanceof ExchangeRateDto) {
                super.setActualInstance(instance);
                return;
            }
        }

        throw new RuntimeException("Invalid instance type. Must be ExchangeRateDto, List<ExchangeRateDto>");
    }

    /**
     * Get the actual instance, which can be the following:
     * ExchangeRateDto, List<ExchangeRateDto>
     *
     * @return The actual instance (ExchangeRateDto, List<ExchangeRateDto>)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `ExchangeRateDto`. If the actual instance is not `ExchangeRateDto`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `ExchangeRateDto`
     * @throws ClassCastException if the instance is not `ExchangeRateDto`
     */
    public ExchangeRateDto getExchangeRateDto() throws ClassCastException {
        return (ExchangeRateDto)super.getActualInstance();
    }

    /**
     * Get the actual instance of `List<ExchangeRateDto>`. If the actual instance is not `List<ExchangeRateDto>`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `List<ExchangeRateDto>`
     * @throws ClassCastException if the instance is not `List<ExchangeRateDto>`
     */
    public List<ExchangeRateDto> getListExchangeRateDto() throws ClassCastException {
        return (List<ExchangeRateDto>)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to List3200Response
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with ExchangeRateDto
        try {
            ExchangeRateDto.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for ExchangeRateDto failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with List<ExchangeRateDto>
        try {
            if (!jsonElement.isJsonArray()) {
                throw new IllegalArgumentException(String.format("Expected json element to be a array type in the JSON string but got `%s`", jsonElement.toString()));
            }
            JsonArray array = jsonElement.getAsJsonArray();
            // validate array items
            for(JsonElement element : array) {
                ExchangeRateDto.validateJsonElement(element);
            }
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for List<ExchangeRateDto> failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format("The JSON string is invalid for List3200Response with oneOf schemas: ExchangeRateDto, List<ExchangeRateDto>. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of List3200Response given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of List3200Response
     * @throws IOException if the JSON string is invalid with respect to List3200Response
     */
    public static List3200Response fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, List3200Response.class);
    }

    /**
     * Convert an instance of List3200Response to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

