/*
 * zipper-pay API
 * Payment service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.pay.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.pay.sdk.JSON;

/**
 * PaymentMethodOptionDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class PaymentMethodOptionDto {
  /**
   * Gets or Sets method
   */
  @JsonAdapter(MethodEnum.Adapter.class)
  public enum MethodEnum {
    WALLET("WALLET"),
    
    PAYME("PAYME");

    private String value;

    MethodEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static MethodEnum fromValue(String value) {
      for (MethodEnum b : MethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<MethodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final MethodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public MethodEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return MethodEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      MethodEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_METHOD = "method";
  @SerializedName(SERIALIZED_NAME_METHOD)
  @javax.annotation.Nullable
  private MethodEnum method;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  @javax.annotation.Nullable
  private String displayName;

  public static final String SERIALIZED_NAME_IFRAME = "iframe";
  @SerializedName(SERIALIZED_NAME_IFRAME)
  @javax.annotation.Nullable
  private Boolean iframe;

  /**
   * Gets or Sets supportedCards
   */
  @JsonAdapter(SupportedCardsEnum.Adapter.class)
  public enum SupportedCardsEnum {
    VISA("VISA"),
    
    MASTERCARD("MASTERCARD");

    private String value;

    SupportedCardsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SupportedCardsEnum fromValue(String value) {
      for (SupportedCardsEnum b : SupportedCardsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SupportedCardsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SupportedCardsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SupportedCardsEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SupportedCardsEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      SupportedCardsEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_SUPPORTED_CARDS = "supportedCards";
  @SerializedName(SERIALIZED_NAME_SUPPORTED_CARDS)
  @javax.annotation.Nullable
  private Set<SupportedCardsEnum> supportedCards = new LinkedHashSet<>();

  public PaymentMethodOptionDto() {
  }

  public PaymentMethodOptionDto method(@javax.annotation.Nullable MethodEnum method) {
    this.method = method;
    return this;
  }

  /**
   * Get method
   * @return method
   */
  @javax.annotation.Nullable
  public MethodEnum getMethod() {
    return method;
  }

  public void setMethod(@javax.annotation.Nullable MethodEnum method) {
    this.method = method;
  }


  public PaymentMethodOptionDto displayName(@javax.annotation.Nullable String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * Get displayName
   * @return displayName
   */
  @javax.annotation.Nullable
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(@javax.annotation.Nullable String displayName) {
    this.displayName = displayName;
  }


  public PaymentMethodOptionDto iframe(@javax.annotation.Nullable Boolean iframe) {
    this.iframe = iframe;
    return this;
  }

  /**
   * Get iframe
   * @return iframe
   */
  @javax.annotation.Nullable
  public Boolean getIframe() {
    return iframe;
  }

  public void setIframe(@javax.annotation.Nullable Boolean iframe) {
    this.iframe = iframe;
  }


  public PaymentMethodOptionDto supportedCards(@javax.annotation.Nullable Set<SupportedCardsEnum> supportedCards) {
    this.supportedCards = supportedCards;
    return this;
  }

  public PaymentMethodOptionDto addSupportedCardsItem(SupportedCardsEnum supportedCardsItem) {
    if (this.supportedCards == null) {
      this.supportedCards = new LinkedHashSet<>();
    }
    this.supportedCards.add(supportedCardsItem);
    return this;
  }

  /**
   * Get supportedCards
   * @return supportedCards
   */
  @javax.annotation.Nullable
  public Set<SupportedCardsEnum> getSupportedCards() {
    return supportedCards;
  }

  public void setSupportedCards(@javax.annotation.Nullable Set<SupportedCardsEnum> supportedCards) {
    this.supportedCards = supportedCards;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentMethodOptionDto paymentMethodOptionDto = (PaymentMethodOptionDto) o;
    return Objects.equals(this.method, paymentMethodOptionDto.method) &&
        Objects.equals(this.displayName, paymentMethodOptionDto.displayName) &&
        Objects.equals(this.iframe, paymentMethodOptionDto.iframe) &&
        Objects.equals(this.supportedCards, paymentMethodOptionDto.supportedCards);
  }

  @Override
  public int hashCode() {
    return Objects.hash(method, displayName, iframe, supportedCards);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentMethodOptionDto {\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    iframe: ").append(toIndentedString(iframe)).append("\n");
    sb.append("    supportedCards: ").append(toIndentedString(supportedCards)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("method");
    openapiFields.add("displayName");
    openapiFields.add("iframe");
    openapiFields.add("supportedCards");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PaymentMethodOptionDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PaymentMethodOptionDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PaymentMethodOptionDto is not found in the empty JSON string", PaymentMethodOptionDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PaymentMethodOptionDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PaymentMethodOptionDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("method") != null && !jsonObj.get("method").isJsonNull()) && !jsonObj.get("method").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `method` to be a primitive type in the JSON string but got `%s`", jsonObj.get("method").toString()));
      }
      // validate the optional field `method`
      if (jsonObj.get("method") != null && !jsonObj.get("method").isJsonNull()) {
        MethodEnum.validateJsonElement(jsonObj.get("method"));
      }
      if ((jsonObj.get("displayName") != null && !jsonObj.get("displayName").isJsonNull()) && !jsonObj.get("displayName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `displayName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("displayName").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("supportedCards") != null && !jsonObj.get("supportedCards").isJsonNull() && !jsonObj.get("supportedCards").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `supportedCards` to be an array in the JSON string but got `%s`", jsonObj.get("supportedCards").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaymentMethodOptionDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaymentMethodOptionDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaymentMethodOptionDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaymentMethodOptionDto.class));

       return (TypeAdapter<T>) new TypeAdapter<PaymentMethodOptionDto>() {
           @Override
           public void write(JsonWriter out, PaymentMethodOptionDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PaymentMethodOptionDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PaymentMethodOptionDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PaymentMethodOptionDto
   * @throws IOException if the JSON string is invalid with respect to PaymentMethodOptionDto
   */
  public static PaymentMethodOptionDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaymentMethodOptionDto.class);
  }

  /**
   * Convert an instance of PaymentMethodOptionDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

