/*
 * zipper-pay API
 * Payment service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.pay.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.zipper.pay.sdk.model.Filter;
import com.zipper.pay.sdk.model.Pagination;
import com.zipper.pay.sdk.model.SortField;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.pay.sdk.JSON;

/**
 * Search request for payment intents, with filtering, sorting, and pagination. **Query Fields** (full-text search): intent id, &#x60;buyerName&#x60;, &#x60;buyerEmail&#x60;, &#x60;providerRef&#x60;, &#x60;userId&#x60; — the id is cast to text so a fragment copied off a truncated column still matches. **Available Filter/Sort Fields:** - &#x60;status&#x60; (PENDING | AWAITING_METHOD_SELECTION | AWAITING_PAYMENT | COMPLETED | FAILED |   EXPIRED | REFUNDED | PARTIALLY_REFUNDED, sortable) - &#x60;purpose&#x60; (WALLET_TOPUP | PRODUCT_PURCHASE | SUBSCRIPTION_RENEWAL | REFUND_WALLET_TOPUP |   REFUND_PRODUCT_PURCHASE | REFUND_SUBSCRIPTION_RENEWAL, sortable) - &#x60;selectedPaymentMethod&#x60; (WALLET | PAYME | APPLE_PAY | GOOGLE_PAY, sortable) - &#x60;consumerService&#x60; (String, sortable) - &#x60;userId&#x60; (String, sortable) - &#x60;buyerEmail&#x60; (String) - &#x60;currency&#x60; (String, sortable) - &#x60;amount&#x60; (BigDecimal, sortable) - &#x60;createdAt&#x60; (Instant, sortable) — the default sort is &#x60;createdAt DESC&#x60; - &#x60;completedAt&#x60; (Instant, sortable) - &#x60;expiresAt&#x60; (Instant) - &#x60;parentIntentId&#x60; (UUID) — set on refund intents; filter on it to list one intent&#39;s refunds  &#x60;id&#x60; is deliberately absent: sorting UUIDs is meaningless and free-text already finds one. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class SearchPaymentIntentsRequest {
  public static final String SERIALIZED_NAME_QUERY = "query";
  @SerializedName(SERIALIZED_NAME_QUERY)
  @javax.annotation.Nullable
  private String query;

  public static final String SERIALIZED_NAME_FILTERS = "filters";
  @SerializedName(SERIALIZED_NAME_FILTERS)
  @javax.annotation.Nullable
  private Map<String, List<Filter>> filters = new HashMap<>();

  public static final String SERIALIZED_NAME_SORT = "sort";
  @SerializedName(SERIALIZED_NAME_SORT)
  @javax.annotation.Nullable
  private List<SortField> sort = new ArrayList<>();

  public static final String SERIALIZED_NAME_PAGINATION = "pagination";
  @SerializedName(SERIALIZED_NAME_PAGINATION)
  @javax.annotation.Nullable
  private Pagination pagination;

  public SearchPaymentIntentsRequest() {
  }

  public SearchPaymentIntentsRequest query(@javax.annotation.Nullable String query) {
    this.query = query;
    return this;
  }

  /**
   * Full-text search query string. Matches against predefined query fields using case-insensitive LIKE.
   * @return query
   */
  @javax.annotation.Nullable
  public String getQuery() {
    return query;
  }

  public void setQuery(@javax.annotation.Nullable String query) {
    this.query = query;
  }


  public SearchPaymentIntentsRequest filters(@javax.annotation.Nullable Map<String, List<Filter>> filters) {
    this.filters = filters;
    return this;
  }

  public SearchPaymentIntentsRequest putFiltersItem(String key, List<Filter> filtersItem) {
    if (this.filters == null) {
      this.filters = new HashMap<>();
    }
    this.filters.put(key, filtersItem);
    return this;
  }

  /**
   * Filter groups with AND/OR logic. Each group contains a list of filter criteria that are combined using the specified operator.
   * @return filters
   */
  @javax.annotation.Nullable
  public Map<String, List<Filter>> getFilters() {
    return filters;
  }

  public void setFilters(@javax.annotation.Nullable Map<String, List<Filter>> filters) {
    this.filters = filters;
  }


  public SearchPaymentIntentsRequest sort(@javax.annotation.Nullable List<SortField> sort) {
    this.sort = sort;
    return this;
  }

  public SearchPaymentIntentsRequest addSortItem(SortField sortItem) {
    if (this.sort == null) {
      this.sort = new ArrayList<>();
    }
    this.sort.add(sortItem);
    return this;
  }

  /**
   * Sort criteria applied in order. Only sortable fields are accepted.
   * @return sort
   */
  @javax.annotation.Nullable
  public List<SortField> getSort() {
    return sort;
  }

  public void setSort(@javax.annotation.Nullable List<SortField> sort) {
    this.sort = sort;
  }


  public SearchPaymentIntentsRequest pagination(@javax.annotation.Nullable Pagination pagination) {
    this.pagination = pagination;
    return this;
  }

  /**
   * Pagination parameters. Page numbers are 1-based.
   * @return pagination
   */
  @javax.annotation.Nullable
  public Pagination getPagination() {
    return pagination;
  }

  public void setPagination(@javax.annotation.Nullable Pagination pagination) {
    this.pagination = pagination;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchPaymentIntentsRequest searchPaymentIntentsRequest = (SearchPaymentIntentsRequest) o;
    return Objects.equals(this.query, searchPaymentIntentsRequest.query) &&
        Objects.equals(this.filters, searchPaymentIntentsRequest.filters) &&
        Objects.equals(this.sort, searchPaymentIntentsRequest.sort) &&
        Objects.equals(this.pagination, searchPaymentIntentsRequest.pagination);
  }

  @Override
  public int hashCode() {
    return Objects.hash(query, filters, sort, pagination);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchPaymentIntentsRequest {\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("query");
    openapiFields.add("filters");
    openapiFields.add("sort");
    openapiFields.add("pagination");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SearchPaymentIntentsRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SearchPaymentIntentsRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SearchPaymentIntentsRequest is not found in the empty JSON string", SearchPaymentIntentsRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SearchPaymentIntentsRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SearchPaymentIntentsRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("query") != null && !jsonObj.get("query").isJsonNull()) && !jsonObj.get("query").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `query` to be a primitive type in the JSON string but got `%s`", jsonObj.get("query").toString()));
      }
      if (jsonObj.get("sort") != null && !jsonObj.get("sort").isJsonNull()) {
        JsonArray jsonArraysort = jsonObj.getAsJsonArray("sort");
        if (jsonArraysort != null) {
          // ensure the json data is an array
          if (!jsonObj.get("sort").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `sort` to be an array in the JSON string but got `%s`", jsonObj.get("sort").toString()));
          }

          // validate the optional field `sort` (array)
          for (int i = 0; i < jsonArraysort.size(); i++) {
            SortField.validateJsonElement(jsonArraysort.get(i));
          };
        }
      }
      // validate the optional field `pagination`
      if (jsonObj.get("pagination") != null && !jsonObj.get("pagination").isJsonNull()) {
        Pagination.validateJsonElement(jsonObj.get("pagination"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SearchPaymentIntentsRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SearchPaymentIntentsRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SearchPaymentIntentsRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SearchPaymentIntentsRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<SearchPaymentIntentsRequest>() {
           @Override
           public void write(JsonWriter out, SearchPaymentIntentsRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SearchPaymentIntentsRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SearchPaymentIntentsRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SearchPaymentIntentsRequest
   * @throws IOException if the JSON string is invalid with respect to SearchPaymentIntentsRequest
   */
  public static SearchPaymentIntentsRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SearchPaymentIntentsRequest.class);
  }

  /**
   * Convert an instance of SearchPaymentIntentsRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

