/*
 * zipper-pay API
 * Payment service
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zipper.pay.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.zipper.pay.sdk.JSON;

/**
 * SubscriptionResponseDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class SubscriptionResponseDto {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private UUID id;

  public static final String SERIALIZED_NAME_PLAN_ID = "planId";
  @SerializedName(SERIALIZED_NAME_PLAN_ID)
  @javax.annotation.Nullable
  private UUID planId;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  @javax.annotation.Nullable
  private String userId;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    PENDING_AUTHORIZATION("PENDING_AUTHORIZATION"),
    
    ACTIVE("ACTIVE"),
    
    PAST_DUE("PAST_DUE"),
    
    PAUSED("PAUSED"),
    
    CANCEL_AT_PERIOD_END("CANCEL_AT_PERIOD_END"),
    
    CANCELED("CANCELED"),
    
    EXPIRED("EXPIRED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private StatusEnum status;

  /**
   * Gets or Sets provider
   */
  @JsonAdapter(ProviderEnum.Adapter.class)
  public enum ProviderEnum {
    PAYME("PAYME");

    private String value;

    ProviderEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ProviderEnum fromValue(String value) {
      for (ProviderEnum b : ProviderEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ProviderEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ProviderEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ProviderEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ProviderEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ProviderEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_PROVIDER = "provider";
  @SerializedName(SERIALIZED_NAME_PROVIDER)
  @javax.annotation.Nullable
  private ProviderEnum provider;

  public static final String SERIALIZED_NAME_PROVIDER_SUBSCRIPTION_ID = "providerSubscriptionId";
  @SerializedName(SERIALIZED_NAME_PROVIDER_SUBSCRIPTION_ID)
  @javax.annotation.Nullable
  private String providerSubscriptionId;

  public static final String SERIALIZED_NAME_PROVIDER_AUTHORIZATION_URL = "providerAuthorizationUrl";
  @SerializedName(SERIALIZED_NAME_PROVIDER_AUTHORIZATION_URL)
  @javax.annotation.Nullable
  private String providerAuthorizationUrl;

  public static final String SERIALIZED_NAME_AMOUNT_CENTS = "amountCents";
  @SerializedName(SERIALIZED_NAME_AMOUNT_CENTS)
  @javax.annotation.Nullable
  private Long amountCents;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  @javax.annotation.Nullable
  private String currency;

  /**
   * Gets or Sets interval
   */
  @JsonAdapter(IntervalEnum.Adapter.class)
  public enum IntervalEnum {
    MONTHLY("MONTHLY"),
    
    YEARLY("YEARLY");

    private String value;

    IntervalEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static IntervalEnum fromValue(String value) {
      for (IntervalEnum b : IntervalEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<IntervalEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final IntervalEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public IntervalEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return IntervalEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      IntervalEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_INTERVAL = "interval";
  @SerializedName(SERIALIZED_NAME_INTERVAL)
  @javax.annotation.Nullable
  private IntervalEnum interval;

  public static final String SERIALIZED_NAME_CURRENT_PERIOD_START = "currentPeriodStart";
  @SerializedName(SERIALIZED_NAME_CURRENT_PERIOD_START)
  @javax.annotation.Nullable
  private OffsetDateTime currentPeriodStart;

  public static final String SERIALIZED_NAME_CURRENT_PERIOD_END = "currentPeriodEnd";
  @SerializedName(SERIALIZED_NAME_CURRENT_PERIOD_END)
  @javax.annotation.Nullable
  private OffsetDateTime currentPeriodEnd;

  public static final String SERIALIZED_NAME_NEXT_BILLING_AT = "nextBillingAt";
  @SerializedName(SERIALIZED_NAME_NEXT_BILLING_AT)
  @javax.annotation.Nullable
  private OffsetDateTime nextBillingAt;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public SubscriptionResponseDto() {
  }

  public SubscriptionResponseDto id(@javax.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public UUID getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable UUID id) {
    this.id = id;
  }


  public SubscriptionResponseDto planId(@javax.annotation.Nullable UUID planId) {
    this.planId = planId;
    return this;
  }

  /**
   * Get planId
   * @return planId
   */
  @javax.annotation.Nullable
  public UUID getPlanId() {
    return planId;
  }

  public void setPlanId(@javax.annotation.Nullable UUID planId) {
    this.planId = planId;
  }


  public SubscriptionResponseDto userId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @javax.annotation.Nullable
  public String getUserId() {
    return userId;
  }

  public void setUserId(@javax.annotation.Nullable String userId) {
    this.userId = userId;
  }


  public SubscriptionResponseDto status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public SubscriptionResponseDto provider(@javax.annotation.Nullable ProviderEnum provider) {
    this.provider = provider;
    return this;
  }

  /**
   * Get provider
   * @return provider
   */
  @javax.annotation.Nullable
  public ProviderEnum getProvider() {
    return provider;
  }

  public void setProvider(@javax.annotation.Nullable ProviderEnum provider) {
    this.provider = provider;
  }


  public SubscriptionResponseDto providerSubscriptionId(@javax.annotation.Nullable String providerSubscriptionId) {
    this.providerSubscriptionId = providerSubscriptionId;
    return this;
  }

  /**
   * Get providerSubscriptionId
   * @return providerSubscriptionId
   */
  @javax.annotation.Nullable
  public String getProviderSubscriptionId() {
    return providerSubscriptionId;
  }

  public void setProviderSubscriptionId(@javax.annotation.Nullable String providerSubscriptionId) {
    this.providerSubscriptionId = providerSubscriptionId;
  }


  public SubscriptionResponseDto providerAuthorizationUrl(@javax.annotation.Nullable String providerAuthorizationUrl) {
    this.providerAuthorizationUrl = providerAuthorizationUrl;
    return this;
  }

  /**
   * Get providerAuthorizationUrl
   * @return providerAuthorizationUrl
   */
  @javax.annotation.Nullable
  public String getProviderAuthorizationUrl() {
    return providerAuthorizationUrl;
  }

  public void setProviderAuthorizationUrl(@javax.annotation.Nullable String providerAuthorizationUrl) {
    this.providerAuthorizationUrl = providerAuthorizationUrl;
  }


  public SubscriptionResponseDto amountCents(@javax.annotation.Nullable Long amountCents) {
    this.amountCents = amountCents;
    return this;
  }

  /**
   * Get amountCents
   * @return amountCents
   */
  @javax.annotation.Nullable
  public Long getAmountCents() {
    return amountCents;
  }

  public void setAmountCents(@javax.annotation.Nullable Long amountCents) {
    this.amountCents = amountCents;
  }


  public SubscriptionResponseDto currency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @javax.annotation.Nullable
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
  }


  public SubscriptionResponseDto interval(@javax.annotation.Nullable IntervalEnum interval) {
    this.interval = interval;
    return this;
  }

  /**
   * Get interval
   * @return interval
   */
  @javax.annotation.Nullable
  public IntervalEnum getInterval() {
    return interval;
  }

  public void setInterval(@javax.annotation.Nullable IntervalEnum interval) {
    this.interval = interval;
  }


  public SubscriptionResponseDto currentPeriodStart(@javax.annotation.Nullable OffsetDateTime currentPeriodStart) {
    this.currentPeriodStart = currentPeriodStart;
    return this;
  }

  /**
   * Get currentPeriodStart
   * @return currentPeriodStart
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCurrentPeriodStart() {
    return currentPeriodStart;
  }

  public void setCurrentPeriodStart(@javax.annotation.Nullable OffsetDateTime currentPeriodStart) {
    this.currentPeriodStart = currentPeriodStart;
  }


  public SubscriptionResponseDto currentPeriodEnd(@javax.annotation.Nullable OffsetDateTime currentPeriodEnd) {
    this.currentPeriodEnd = currentPeriodEnd;
    return this;
  }

  /**
   * Get currentPeriodEnd
   * @return currentPeriodEnd
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCurrentPeriodEnd() {
    return currentPeriodEnd;
  }

  public void setCurrentPeriodEnd(@javax.annotation.Nullable OffsetDateTime currentPeriodEnd) {
    this.currentPeriodEnd = currentPeriodEnd;
  }


  public SubscriptionResponseDto nextBillingAt(@javax.annotation.Nullable OffsetDateTime nextBillingAt) {
    this.nextBillingAt = nextBillingAt;
    return this;
  }

  /**
   * Get nextBillingAt
   * @return nextBillingAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getNextBillingAt() {
    return nextBillingAt;
  }

  public void setNextBillingAt(@javax.annotation.Nullable OffsetDateTime nextBillingAt) {
    this.nextBillingAt = nextBillingAt;
  }


  public SubscriptionResponseDto createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionResponseDto subscriptionResponseDto = (SubscriptionResponseDto) o;
    return Objects.equals(this.id, subscriptionResponseDto.id) &&
        Objects.equals(this.planId, subscriptionResponseDto.planId) &&
        Objects.equals(this.userId, subscriptionResponseDto.userId) &&
        Objects.equals(this.status, subscriptionResponseDto.status) &&
        Objects.equals(this.provider, subscriptionResponseDto.provider) &&
        Objects.equals(this.providerSubscriptionId, subscriptionResponseDto.providerSubscriptionId) &&
        Objects.equals(this.providerAuthorizationUrl, subscriptionResponseDto.providerAuthorizationUrl) &&
        Objects.equals(this.amountCents, subscriptionResponseDto.amountCents) &&
        Objects.equals(this.currency, subscriptionResponseDto.currency) &&
        Objects.equals(this.interval, subscriptionResponseDto.interval) &&
        Objects.equals(this.currentPeriodStart, subscriptionResponseDto.currentPeriodStart) &&
        Objects.equals(this.currentPeriodEnd, subscriptionResponseDto.currentPeriodEnd) &&
        Objects.equals(this.nextBillingAt, subscriptionResponseDto.nextBillingAt) &&
        Objects.equals(this.createdAt, subscriptionResponseDto.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, planId, userId, status, provider, providerSubscriptionId, providerAuthorizationUrl, amountCents, currency, interval, currentPeriodStart, currentPeriodEnd, nextBillingAt, createdAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionResponseDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    planId: ").append(toIndentedString(planId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    providerSubscriptionId: ").append(toIndentedString(providerSubscriptionId)).append("\n");
    sb.append("    providerAuthorizationUrl: ").append(toIndentedString(providerAuthorizationUrl)).append("\n");
    sb.append("    amountCents: ").append(toIndentedString(amountCents)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    sb.append("    currentPeriodStart: ").append(toIndentedString(currentPeriodStart)).append("\n");
    sb.append("    currentPeriodEnd: ").append(toIndentedString(currentPeriodEnd)).append("\n");
    sb.append("    nextBillingAt: ").append(toIndentedString(nextBillingAt)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("planId");
    openapiFields.add("userId");
    openapiFields.add("status");
    openapiFields.add("provider");
    openapiFields.add("providerSubscriptionId");
    openapiFields.add("providerAuthorizationUrl");
    openapiFields.add("amountCents");
    openapiFields.add("currency");
    openapiFields.add("interval");
    openapiFields.add("currentPeriodStart");
    openapiFields.add("currentPeriodEnd");
    openapiFields.add("nextBillingAt");
    openapiFields.add("createdAt");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SubscriptionResponseDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SubscriptionResponseDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SubscriptionResponseDto is not found in the empty JSON string", SubscriptionResponseDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SubscriptionResponseDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SubscriptionResponseDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("planId") != null && !jsonObj.get("planId").isJsonNull()) && !jsonObj.get("planId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `planId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("planId").toString()));
      }
      if ((jsonObj.get("userId") != null && !jsonObj.get("userId").isJsonNull()) && !jsonObj.get("userId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `userId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userId").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `status`
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) {
        StatusEnum.validateJsonElement(jsonObj.get("status"));
      }
      if ((jsonObj.get("provider") != null && !jsonObj.get("provider").isJsonNull()) && !jsonObj.get("provider").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `provider` to be a primitive type in the JSON string but got `%s`", jsonObj.get("provider").toString()));
      }
      // validate the optional field `provider`
      if (jsonObj.get("provider") != null && !jsonObj.get("provider").isJsonNull()) {
        ProviderEnum.validateJsonElement(jsonObj.get("provider"));
      }
      if ((jsonObj.get("providerSubscriptionId") != null && !jsonObj.get("providerSubscriptionId").isJsonNull()) && !jsonObj.get("providerSubscriptionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `providerSubscriptionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("providerSubscriptionId").toString()));
      }
      if ((jsonObj.get("providerAuthorizationUrl") != null && !jsonObj.get("providerAuthorizationUrl").isJsonNull()) && !jsonObj.get("providerAuthorizationUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `providerAuthorizationUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("providerAuthorizationUrl").toString()));
      }
      if ((jsonObj.get("currency") != null && !jsonObj.get("currency").isJsonNull()) && !jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
      if ((jsonObj.get("interval") != null && !jsonObj.get("interval").isJsonNull()) && !jsonObj.get("interval").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `interval` to be a primitive type in the JSON string but got `%s`", jsonObj.get("interval").toString()));
      }
      // validate the optional field `interval`
      if (jsonObj.get("interval") != null && !jsonObj.get("interval").isJsonNull()) {
        IntervalEnum.validateJsonElement(jsonObj.get("interval"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SubscriptionResponseDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SubscriptionResponseDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SubscriptionResponseDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SubscriptionResponseDto.class));

       return (TypeAdapter<T>) new TypeAdapter<SubscriptionResponseDto>() {
           @Override
           public void write(JsonWriter out, SubscriptionResponseDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SubscriptionResponseDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SubscriptionResponseDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SubscriptionResponseDto
   * @throws IOException if the JSON string is invalid with respect to SubscriptionResponseDto
   */
  public static SubscriptionResponseDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SubscriptionResponseDto.class);
  }

  /**
   * Convert an instance of SubscriptionResponseDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

